---
- name: Ensure munin-node is installed because it includes munin-async (Red Hat and derivatives).
  yum: name=munin-node state=present enablerepo=epel

- name: Create munin-async user on Red Hat and derivatives.
  user:
    name: "{{ munin_async_user }}"
    system: true
    home: "{{ munin_async_home }}"
