---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include SELinux configuration if necessary.
  include_tasks: selinux.yml
  when: "'mode' in ansible_facts.selinux and ansible_facts.selinux.mode == 'enforcing'"

- name: Include Red-Hat based installation steps.
  include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian based installation steps.
  include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Test that the munin-async client binary exists.
  file: path={{ munin_async_clientbin }} state=file

- name: Ensure ~/.ssh/ exists for the munin-async user.
  file:
    path: "{{ munin_async_home }}/.ssh/"
    state: directory
    owner: "{{ munin_async_user }}"
    group: "{{ munin_async_group }}"
    mode: 0700

- name: Add SSH key to munin-async user.
  template:
    src: munin-async-authorized_keys.j2
    dest: "{{ munin_async_home }}/.ssh/authorized_keys"
    owner: "{{ munin_async_user }}"
    group: "{{ munin_async_group }}"
    mode: 0600
  when: munin_async_sshpubkeys != []

- name: Ensure munin-async is running.
  service: name={{ munin_async_service }} state=started enabled=yes
