---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure munin-async is installed (CentOS 7).
  yum: name=munin-async state=present enablerepo=epel
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"

- name: Ensure munin-async is installed through munin-node (CentOS 8).
  yum: name=munin-node state=present enablerepo=epel
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "8"

- name: Ensure munin-async is installed (Debian and derivatives).
  apt: name=munin-async state=present
  when: ansible_os_family == 'Debian'

- name: Create munin-async user on CentOS
  user:
    name: "{{ munin_async_user }}"
    system: true
    home: "{{ munin_async_home }}"
  when: ansible_os_family == 'RedHat'

- name: Ensure ~/.ssh/ exists for munin-async user
  file:
    path: "{{ munin_async_home }}/.ssh/"
    state: directory
    owner: "{{ munin_async_user }}"
    group: "{{ munin_async_group }}"
    mode: 0700

- name: Add SSH key to munin-async user
  template:
    src: munin-async-authorized_keys.j2
    dest: "{{ munin_async_home }}/.ssh/authorized_keys"
    owner: "{{ munin_async_user }}"
    group: "{{ munin_async_group }}"
    mode: 0600
  when: munin_async_sshpubkeys

- name: Ensure munin-async is running.
  service: name={{ munin_async_service }} state=started enabled=yes
