---
# See https://github.com/munin-monitoring/munin/issues/1309
- name: Copy muninasync selinux policy if in enforcing mode.
  copy:
    src: munin-async/muninasync.pp
    dest: /tmp/muninasync.pp

- name: Check if the muninasync selinux policy is already loaded.
  command:
    cmd: semodule -l
  register: semodule_out
  check_mode: no
  changed_when: "'muninasync' not in semodule_out.stdout"

- name: Load muninasync selinux policy if needed.
  command:
    cmd: semodule -i /tmp/muninasync.pp
  when: "'muninasync' not in semodule_out.stdout"
